import styles from '../styles/Home.module.css'
import '../styles/globals.css'
import Image from 'next/image'
import salmon from '../public/salmon.png';
import Link from 'next/link'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="font" />
      </Head>
    <header className={styles.header}>
        <h1>Salmon Cookies</h1>
        <nav>
          <Image 
            src={salmon} 
            alt="a dark brown and orange salmon"
            width={(500)}
            height={(200)}
          />
          
          <Link href="/sales">Sales Data </Link>
          <Link href="/"> Home</Link>
          <Image 
            src="/../public/chinook.jpeg" 
            alt="a dark brown chinook"
            width={(500)}
            height={(200)}
          />
        </nav>
      </header>
  <Component {...pageProps} />
  <footer className={styles.footer}>
        <h3>Contact Info: salmoncookies@gmail.com or call me at 555-111-4090</h3>
      </footer>
    </>
  )
}

export default MyApp
