import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import salmon from '../public/salmon.png';
import Link from 'next/link'

export default function Home() {
  return (
        <div className={styles.container}>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>Salmon Cookies</h1>
        <nav>
          <Image 
            src={salmon} 
            alt="a dark brown and orange salmon"
            width={(500)}
            height={(200)}
          />
          <Link href="/sales">Sales Data </Link>
          <Link href="/home"> Home</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <section>
          <h2 className={styles.title}>
            Hours
          </h2>
          <p>All locations are open from 9am to 6pm</p>
        </section>
        <div className={styles.container}>
          <section>
            <h2 className={styles.title}>Locations</h2>
            <ul> 
            <li> 416 Sid Snyder Avenue SW, Olympia, Washington 98504</li>
            <li> 1-5-2 Higashi Shimbashi, Minato-ku, Tokyo</li>
            <li> Al Thanyah 1, Hadaeq Mohammed Bin Rashid, Dubai</li>
            <li> 22, 24 Basil St, Paris</li>
            <li> Jr. Cayetano Heredia 135, Jesus Maria, Lima, Peru</li> 
            </ul>
          </section>
        </div>
          <article>
            <section>
              <h3>A little about us!</h3>
              <p> Thank you so much for your interest in salmon cookies! I have been waiting so long to share this amazing recipe with all of you internationally! This journey began in 2007 when my husband Ken, myself, and our two children combined our love for fish and cookies together to create what is known as salmon cookies today. We source our dry ingredients from local farms across the world and fish for salmon on our own chartered boats. Every step in the process to building our fish cookie empire has had your enjoyment in mind! We have locations in Seattle, Tokyo, Dubai, Paris, and Lima .  
              </p>
            </section>
            {/* <a href="">Some Button</a> */}
          </article>
      </main>
      <footer className={styles.footer}>
        <h3>Contact Info: salmoncookies@gmail.com or call me at 555-111-4090</h3>
      </footer>
      </div>
  )
}
